# Generated by Django 5.0.7 on 2024-08-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Register',
        ),
    ]
